namespace QuanLyThuVienSach.GUI
{
    partial class EditResume
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(EditResume));
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.Rb_Female = new Bunifu.UI.WinForms.BunifuRadioButton();
            this.label9 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.Rb_Male = new Bunifu.UI.WinForms.BunifuRadioButton();
            this.bt_Exit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.DatePicker_DOB = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bt_Clear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bt_SaveResume = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.tb_Phone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_Email = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_Address = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_Name = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel11 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bt_Save = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel7 = new Bunifu.UI.WinForms.BunifuPanel();
            this.panel1.SuspendLayout();
            this.bunifuGroupBox1.SuspendLayout();
            this.bunifuPanel7.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.Color.White;
            this.label7.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label7.Location = new System.Drawing.Point(118, 188);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(42, 16);
            this.label7.TabIndex = 33;
            this.label7.Text = "Phone";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.White;
            this.label6.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label6.Location = new System.Drawing.Point(481, 137);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(36, 16);
            this.label6.TabIndex = 32;
            this.label6.Text = "Email";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.White;
            this.label5.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label5.Location = new System.Drawing.Point(481, 86);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(58, 16);
            this.label5.TabIndex = 31;
            this.label5.Text = "Anddress";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.White;
            this.label4.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label4.Location = new System.Drawing.Point(481, 187);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(81, 16);
            this.label4.TabIndex = 30;
            this.label4.Text = "Data Of Birth";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.White;
            this.label3.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label3.Location = new System.Drawing.Point(111, 138);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(49, 16);
            this.label3.TabIndex = 29;
            this.label3.Text = "Gender";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.White;
            this.label2.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label2.Location = new System.Drawing.Point(120, 88);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(40, 16);
            this.label2.TabIndex = 28;
            this.label2.Text = "Name";
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.panel1.Controls.Add(this.bunifuLabel1);
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(900, 45);
            this.panel1.TabIndex = 40;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Microsoft Tai Le", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.DarkGray;
            this.bunifuLabel1.Location = new System.Drawing.Point(15, 14);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(82, 19);
            this.bunifuLabel1.TabIndex = 129;
            this.bunifuLabel1.Text = "Edit Resume";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.panel2.Location = new System.Drawing.Point(31, 400);
            this.panel2.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(900, 48);
            this.panel2.TabIndex = 45;
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.bunifuGroupBox1.BorderRadius = 7;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.Rb_Female);
            this.bunifuGroupBox1.Controls.Add(this.label9);
            this.bunifuGroupBox1.Controls.Add(this.label8);
            this.bunifuGroupBox1.Controls.Add(this.Rb_Male);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Microsoft Tai Le", 9F);
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(177, 124);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(255, 38);
            this.bunifuGroupBox1.TabIndex = 68;
            this.bunifuGroupBox1.TabStop = false;
            // 
            // Rb_Female
            // 
            this.Rb_Female.AllowBindingControlLocation = false;
            this.Rb_Female.BackColor = System.Drawing.Color.Transparent;
            this.Rb_Female.BindingControlPosition = Bunifu.UI.WinForms.BunifuRadioButton.BindingControlPositions.Right;
            this.Rb_Female.BorderThickness = 1;
            this.Rb_Female.Checked = false;
            this.Rb_Female.Location = new System.Drawing.Point(111, 8);
            this.Rb_Female.Name = "Rb_Female";
            this.Rb_Female.OutlineColor = System.Drawing.Color.DodgerBlue;
            this.Rb_Female.OutlineColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Rb_Female.OutlineColorUnchecked = System.Drawing.Color.DarkGray;
            this.Rb_Female.RadioColor = System.Drawing.Color.DodgerBlue;
            this.Rb_Female.RadioColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Rb_Female.Size = new System.Drawing.Size(21, 21);
            this.Rb_Female.TabIndex = 70;
            this.Rb_Female.Text = null;
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.BackColor = System.Drawing.Color.White;
            this.label9.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label9.Location = new System.Drawing.Point(134, 11);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(47, 16);
            this.label9.TabIndex = 69;
            this.label9.Text = "Female";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.BackColor = System.Drawing.Color.White;
            this.label8.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label8.Location = new System.Drawing.Point(44, 11);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(34, 16);
            this.label8.TabIndex = 68;
            this.label8.Text = "Male";
            // 
            // Rb_Male
            // 
            this.Rb_Male.AllowBindingControlLocation = false;
            this.Rb_Male.BackColor = System.Drawing.Color.Transparent;
            this.Rb_Male.BindingControlPosition = Bunifu.UI.WinForms.BunifuRadioButton.BindingControlPositions.Right;
            this.Rb_Male.BorderThickness = 1;
            this.Rb_Male.Checked = true;
            this.Rb_Male.Location = new System.Drawing.Point(17, 8);
            this.Rb_Male.Name = "Rb_Male";
            this.Rb_Male.OutlineColor = System.Drawing.Color.DodgerBlue;
            this.Rb_Male.OutlineColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Rb_Male.OutlineColorUnchecked = System.Drawing.Color.DarkGray;
            this.Rb_Male.RadioColor = System.Drawing.Color.DodgerBlue;
            this.Rb_Male.RadioColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Rb_Male.Size = new System.Drawing.Size(21, 21);
            this.Rb_Male.TabIndex = 0;
            this.Rb_Male.Text = null;
            // 
            // bt_Exit
            // 
            this.bt_Exit.AllowAnimations = true;
            this.bt_Exit.AllowMouseEffects = true;
            this.bt_Exit.AllowToggling = false;
            this.bt_Exit.AnimationSpeed = 200;
            this.bt_Exit.AutoGenerateColors = false;
            this.bt_Exit.AutoRoundBorders = false;
            this.bt_Exit.AutoSizeLeftIcon = true;
            this.bt_Exit.AutoSizeRightIcon = true;
            this.bt_Exit.BackColor = System.Drawing.Color.Transparent;
            this.bt_Exit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(50)))));
            this.bt_Exit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bt_Exit.BackgroundImage")));
            this.bt_Exit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.ButtonText = "Exit";
            this.bt_Exit.ButtonTextMarginLeft = 0;
            this.bt_Exit.ColorContrastOnClick = 45;
            this.bt_Exit.ColorContrastOnHover = 45;
            this.bt_Exit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bt_Exit.CustomizableEdges = borderEdges2;
            this.bt_Exit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bt_Exit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_Exit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_Exit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_Exit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bt_Exit.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bt_Exit.ForeColor = System.Drawing.Color.DarkGray;
            this.bt_Exit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bt_Exit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bt_Exit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bt_Exit.IconMarginLeft = 11;
            this.bt_Exit.IconPadding = 14;
            this.bt_Exit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bt_Exit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bt_Exit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bt_Exit.IconSize = 5;
            this.bt_Exit.IdleBorderColor = System.Drawing.Color.Black;
            this.bt_Exit.IdleBorderRadius = 5;
            this.bt_Exit.IdleBorderThickness = 2;
            this.bt_Exit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(50)))));
            this.bt_Exit.IdleIconLeftImage = null;
            this.bt_Exit.IdleIconRightImage = null;
            this.bt_Exit.IndicateFocus = false;
            this.bt_Exit.Location = new System.Drawing.Point(634, 310);
            this.bt_Exit.Name = "bt_Exit";
            this.bt_Exit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_Exit.OnDisabledState.BorderRadius = 5;
            this.bt_Exit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.OnDisabledState.BorderThickness = 2;
            this.bt_Exit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_Exit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_Exit.OnDisabledState.IconLeftImage = null;
            this.bt_Exit.OnDisabledState.IconRightImage = null;
            this.bt_Exit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_Exit.onHoverState.BorderRadius = 5;
            this.bt_Exit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.onHoverState.BorderThickness = 2;
            this.bt_Exit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_Exit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bt_Exit.onHoverState.IconLeftImage = null;
            this.bt_Exit.onHoverState.IconRightImage = null;
            this.bt_Exit.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bt_Exit.OnIdleState.BorderRadius = 5;
            this.bt_Exit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.OnIdleState.BorderThickness = 2;
            this.bt_Exit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(50)))));
            this.bt_Exit.OnIdleState.ForeColor = System.Drawing.Color.DarkGray;
            this.bt_Exit.OnIdleState.IconLeftImage = null;
            this.bt_Exit.OnIdleState.IconRightImage = null;
            this.bt_Exit.OnPressedState.BorderColor = System.Drawing.Color.Silver;
            this.bt_Exit.OnPressedState.BorderRadius = 5;
            this.bt_Exit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.OnPressedState.BorderThickness = 2;
            this.bt_Exit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_Exit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bt_Exit.OnPressedState.IconLeftImage = null;
            this.bt_Exit.OnPressedState.IconRightImage = null;
            this.bt_Exit.Size = new System.Drawing.Size(172, 40);
            this.bt_Exit.TabIndex = 69;
            this.bt_Exit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bt_Exit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bt_Exit.TextMarginLeft = 0;
            this.bt_Exit.TextPadding = new System.Windows.Forms.Padding(0);
            this.bt_Exit.UseDefaultRadiusAndThickness = true;
            this.bt_Exit.Click += new System.EventHandler(this.bt_Exit_Click);
            // 
            // DatePicker_DOB
            // 
            this.DatePicker_DOB.BackColor = System.Drawing.Color.Transparent;
            this.DatePicker_DOB.BorderColor = System.Drawing.Color.White;
            this.DatePicker_DOB.BorderRadius = 5;
            this.DatePicker_DOB.CalendarFont = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DatePicker_DOB.CalendarForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.DatePicker_DOB.CalendarMonthBackground = System.Drawing.Color.Silver;
            this.DatePicker_DOB.CalendarTitleBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.DatePicker_DOB.CalendarTitleForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.DatePicker_DOB.Color = System.Drawing.Color.White;
            this.DatePicker_DOB.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.DatePicker_DOB.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.DatePicker_DOB.DisabledColor = System.Drawing.Color.Gray;
            this.DatePicker_DOB.DisplayWeekNumbers = false;
            this.DatePicker_DOB.DPHeight = 0;
            this.DatePicker_DOB.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.DatePicker_DOB.FillDatePicker = false;
            this.DatePicker_DOB.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DatePicker_DOB.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.DatePicker_DOB.Icon = ((System.Drawing.Image)(resources.GetObject("DatePicker_DOB.Icon")));
            this.DatePicker_DOB.IconColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.DatePicker_DOB.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.DatePicker_DOB.LeftTextMargin = 0;
            this.DatePicker_DOB.Location = new System.Drawing.Point(7, 4);
            this.DatePicker_DOB.MinimumSize = new System.Drawing.Size(4, 32);
            this.DatePicker_DOB.Name = "DatePicker_DOB";
            this.DatePicker_DOB.Size = new System.Drawing.Size(235, 32);
            this.DatePicker_DOB.TabIndex = 47;
            this.DatePicker_DOB.Value = new System.DateTime(2022, 4, 8, 21, 49, 0, 0);
            // 
            // bt_Clear
            // 
            this.bt_Clear.AllowAnimations = true;
            this.bt_Clear.AllowMouseEffects = true;
            this.bt_Clear.AllowToggling = false;
            this.bt_Clear.AnimationSpeed = 200;
            this.bt_Clear.AutoGenerateColors = false;
            this.bt_Clear.AutoRoundBorders = false;
            this.bt_Clear.AutoSizeLeftIcon = true;
            this.bt_Clear.AutoSizeRightIcon = true;
            this.bt_Clear.BackColor = System.Drawing.Color.Transparent;
            this.bt_Clear.BackColor1 = System.Drawing.Color.White;
            this.bt_Clear.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bt_Clear.BackgroundImage")));
            this.bt_Clear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Clear.ButtonText = "Clear";
            this.bt_Clear.ButtonTextMarginLeft = 0;
            this.bt_Clear.ColorContrastOnClick = 45;
            this.bt_Clear.ColorContrastOnHover = 45;
            this.bt_Clear.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bt_Clear.CustomizableEdges = borderEdges5;
            this.bt_Clear.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bt_Clear.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_Clear.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_Clear.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_Clear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bt_Clear.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bt_Clear.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_Clear.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bt_Clear.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bt_Clear.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bt_Clear.IconMarginLeft = 11;
            this.bt_Clear.IconPadding = 14;
            this.bt_Clear.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bt_Clear.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bt_Clear.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bt_Clear.IconSize = 5;
            this.bt_Clear.IdleBorderColor = System.Drawing.Color.DimGray;
            this.bt_Clear.IdleBorderRadius = 5;
            this.bt_Clear.IdleBorderThickness = 2;
            this.bt_Clear.IdleFillColor = System.Drawing.Color.White;
            this.bt_Clear.IdleIconLeftImage = null;
            this.bt_Clear.IdleIconRightImage = null;
            this.bt_Clear.IndicateFocus = false;
            this.bt_Clear.Location = new System.Drawing.Point(177, 310);
            this.bt_Clear.Name = "bt_Clear";
            this.bt_Clear.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_Clear.OnDisabledState.BorderRadius = 5;
            this.bt_Clear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Clear.OnDisabledState.BorderThickness = 2;
            this.bt_Clear.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_Clear.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_Clear.OnDisabledState.IconLeftImage = null;
            this.bt_Clear.OnDisabledState.IconRightImage = null;
            this.bt_Clear.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_Clear.onHoverState.BorderRadius = 5;
            this.bt_Clear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Clear.onHoverState.BorderThickness = 2;
            this.bt_Clear.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_Clear.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bt_Clear.onHoverState.IconLeftImage = null;
            this.bt_Clear.onHoverState.IconRightImage = null;
            this.bt_Clear.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.bt_Clear.OnIdleState.BorderRadius = 5;
            this.bt_Clear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Clear.OnIdleState.BorderThickness = 2;
            this.bt_Clear.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bt_Clear.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_Clear.OnIdleState.IconLeftImage = null;
            this.bt_Clear.OnIdleState.IconRightImage = null;
            this.bt_Clear.OnPressedState.BorderColor = System.Drawing.Color.Silver;
            this.bt_Clear.OnPressedState.BorderRadius = 5;
            this.bt_Clear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Clear.OnPressedState.BorderThickness = 2;
            this.bt_Clear.OnPressedState.FillColor = System.Drawing.Color.White;
            this.bt_Clear.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_Clear.OnPressedState.IconLeftImage = null;
            this.bt_Clear.OnPressedState.IconRightImage = null;
            this.bt_Clear.Size = new System.Drawing.Size(172, 40);
            this.bt_Clear.TabIndex = 43;
            this.bt_Clear.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bt_Clear.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bt_Clear.TextMarginLeft = 0;
            this.bt_Clear.TextPadding = new System.Windows.Forms.Padding(0);
            this.bt_Clear.UseDefaultRadiusAndThickness = true;
            // 
            // bt_SaveResume
            // 
            this.bt_SaveResume.AllowAnimations = true;
            this.bt_SaveResume.AllowMouseEffects = true;
            this.bt_SaveResume.AllowToggling = false;
            this.bt_SaveResume.AnimationSpeed = 200;
            this.bt_SaveResume.AutoGenerateColors = false;
            this.bt_SaveResume.AutoRoundBorders = false;
            this.bt_SaveResume.AutoSizeLeftIcon = true;
            this.bt_SaveResume.AutoSizeRightIcon = true;
            this.bt_SaveResume.BackColor = System.Drawing.Color.Transparent;
            this.bt_SaveResume.BackColor1 = System.Drawing.Color.White;
            this.bt_SaveResume.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bt_SaveResume.BackgroundImage")));
            this.bt_SaveResume.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_SaveResume.ButtonText = "Save Resume";
            this.bt_SaveResume.ButtonTextMarginLeft = 0;
            this.bt_SaveResume.ColorContrastOnClick = 45;
            this.bt_SaveResume.ColorContrastOnHover = 45;
            this.bt_SaveResume.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bt_SaveResume.CustomizableEdges = borderEdges6;
            this.bt_SaveResume.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bt_SaveResume.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_SaveResume.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_SaveResume.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_SaveResume.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bt_SaveResume.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bt_SaveResume.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_SaveResume.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bt_SaveResume.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bt_SaveResume.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bt_SaveResume.IconMarginLeft = 11;
            this.bt_SaveResume.IconPadding = 14;
            this.bt_SaveResume.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bt_SaveResume.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bt_SaveResume.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bt_SaveResume.IconSize = 5;
            this.bt_SaveResume.IdleBorderColor = System.Drawing.Color.DimGray;
            this.bt_SaveResume.IdleBorderRadius = 5;
            this.bt_SaveResume.IdleBorderThickness = 2;
            this.bt_SaveResume.IdleFillColor = System.Drawing.Color.White;
            this.bt_SaveResume.IdleIconLeftImage = null;
            this.bt_SaveResume.IdleIconRightImage = null;
            this.bt_SaveResume.IndicateFocus = false;
            this.bt_SaveResume.Location = new System.Drawing.Point(407, 310);
            this.bt_SaveResume.Name = "bt_SaveResume";
            this.bt_SaveResume.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_SaveResume.OnDisabledState.BorderRadius = 5;
            this.bt_SaveResume.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_SaveResume.OnDisabledState.BorderThickness = 2;
            this.bt_SaveResume.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_SaveResume.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_SaveResume.OnDisabledState.IconLeftImage = null;
            this.bt_SaveResume.OnDisabledState.IconRightImage = null;
            this.bt_SaveResume.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_SaveResume.onHoverState.BorderRadius = 5;
            this.bt_SaveResume.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_SaveResume.onHoverState.BorderThickness = 2;
            this.bt_SaveResume.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_SaveResume.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bt_SaveResume.onHoverState.IconLeftImage = null;
            this.bt_SaveResume.onHoverState.IconRightImage = null;
            this.bt_SaveResume.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.bt_SaveResume.OnIdleState.BorderRadius = 5;
            this.bt_SaveResume.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_SaveResume.OnIdleState.BorderThickness = 2;
            this.bt_SaveResume.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bt_SaveResume.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_SaveResume.OnIdleState.IconLeftImage = null;
            this.bt_SaveResume.OnIdleState.IconRightImage = null;
            this.bt_SaveResume.OnPressedState.BorderColor = System.Drawing.Color.Silver;
            this.bt_SaveResume.OnPressedState.BorderRadius = 5;
            this.bt_SaveResume.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_SaveResume.OnPressedState.BorderThickness = 2;
            this.bt_SaveResume.OnPressedState.FillColor = System.Drawing.Color.White;
            this.bt_SaveResume.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_SaveResume.OnPressedState.IconLeftImage = null;
            this.bt_SaveResume.OnPressedState.IconRightImage = null;
            this.bt_SaveResume.Size = new System.Drawing.Size(172, 40);
            this.bt_SaveResume.TabIndex = 42;
            this.bt_SaveResume.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bt_SaveResume.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bt_SaveResume.TextMarginLeft = 0;
            this.bt_SaveResume.TextPadding = new System.Windows.Forms.Padding(0);
            this.bt_SaveResume.UseDefaultRadiusAndThickness = true;
            // 
            // tb_Phone
            // 
            this.tb_Phone.AcceptsReturn = false;
            this.tb_Phone.AcceptsTab = false;
            this.tb_Phone.AnimationSpeed = 200;
            this.tb_Phone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_Phone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_Phone.AutoSizeHeight = true;
            this.tb_Phone.BackColor = System.Drawing.Color.Transparent;
            this.tb_Phone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_Phone.BackgroundImage")));
            this.tb_Phone.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_Phone.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_Phone.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_Phone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_Phone.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_Phone.BorderRadius = 15;
            this.tb_Phone.BorderThickness = 1;
            this.tb_Phone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_Phone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Phone.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_Phone.DefaultText = "";
            this.tb_Phone.FillColor = System.Drawing.Color.White;
            this.tb_Phone.HideSelection = true;
            this.tb_Phone.IconLeft = null;
            this.tb_Phone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Phone.IconPadding = 10;
            this.tb_Phone.IconRight = null;
            this.tb_Phone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Phone.Lines = new string[0];
            this.tb_Phone.Location = new System.Drawing.Point(177, 176);
            this.tb_Phone.MaxLength = 32767;
            this.tb_Phone.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_Phone.Modified = false;
            this.tb_Phone.Multiline = false;
            this.tb_Phone.Name = "tb_Phone";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Phone.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Silver;
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_Phone.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Phone.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Phone.OnIdleState = stateProperties4;
            this.tb_Phone.Padding = new System.Windows.Forms.Padding(3);
            this.tb_Phone.PasswordChar = '\0';
            this.tb_Phone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_Phone.PlaceholderText = "";
            this.tb_Phone.ReadOnly = false;
            this.tb_Phone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_Phone.SelectedText = "";
            this.tb_Phone.SelectionLength = 0;
            this.tb_Phone.SelectionStart = 0;
            this.tb_Phone.ShortcutsEnabled = true;
            this.tb_Phone.Size = new System.Drawing.Size(255, 38);
            this.tb_Phone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_Phone.TabIndex = 41;
            this.tb_Phone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_Phone.TextMarginBottom = 0;
            this.tb_Phone.TextMarginLeft = 3;
            this.tb_Phone.TextMarginTop = 1;
            this.tb_Phone.TextPlaceholder = "";
            this.tb_Phone.UseSystemPasswordChar = false;
            this.tb_Phone.WordWrap = true;
            // 
            // tb_Email
            // 
            this.tb_Email.AcceptsReturn = false;
            this.tb_Email.AcceptsTab = false;
            this.tb_Email.AnimationSpeed = 200;
            this.tb_Email.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_Email.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_Email.AutoSizeHeight = true;
            this.tb_Email.BackColor = System.Drawing.Color.Transparent;
            this.tb_Email.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_Email.BackgroundImage")));
            this.tb_Email.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_Email.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_Email.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_Email.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_Email.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_Email.BorderRadius = 15;
            this.tb_Email.BorderThickness = 1;
            this.tb_Email.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_Email.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Email.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_Email.DefaultText = "";
            this.tb_Email.FillColor = System.Drawing.Color.White;
            this.tb_Email.HideSelection = true;
            this.tb_Email.IconLeft = null;
            this.tb_Email.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Email.IconPadding = 10;
            this.tb_Email.IconRight = null;
            this.tb_Email.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Email.Lines = new string[0];
            this.tb_Email.Location = new System.Drawing.Point(577, 124);
            this.tb_Email.MaxLength = 32767;
            this.tb_Email.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_Email.Modified = false;
            this.tb_Email.Multiline = false;
            this.tb_Email.Name = "tb_Email";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Email.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Silver;
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_Email.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Email.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Email.OnIdleState = stateProperties8;
            this.tb_Email.Padding = new System.Windows.Forms.Padding(3);
            this.tb_Email.PasswordChar = '\0';
            this.tb_Email.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_Email.PlaceholderText = "";
            this.tb_Email.ReadOnly = false;
            this.tb_Email.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_Email.SelectedText = "";
            this.tb_Email.SelectionLength = 0;
            this.tb_Email.SelectionStart = 0;
            this.tb_Email.ShortcutsEnabled = true;
            this.tb_Email.Size = new System.Drawing.Size(255, 38);
            this.tb_Email.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_Email.TabIndex = 40;
            this.tb_Email.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_Email.TextMarginBottom = 0;
            this.tb_Email.TextMarginLeft = 3;
            this.tb_Email.TextMarginTop = 1;
            this.tb_Email.TextPlaceholder = "";
            this.tb_Email.UseSystemPasswordChar = false;
            this.tb_Email.WordWrap = true;
            // 
            // tb_Address
            // 
            this.tb_Address.AcceptsReturn = false;
            this.tb_Address.AcceptsTab = false;
            this.tb_Address.AnimationSpeed = 200;
            this.tb_Address.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_Address.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_Address.AutoSizeHeight = true;
            this.tb_Address.BackColor = System.Drawing.Color.Transparent;
            this.tb_Address.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_Address.BackgroundImage")));
            this.tb_Address.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_Address.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_Address.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_Address.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_Address.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_Address.BorderRadius = 15;
            this.tb_Address.BorderThickness = 1;
            this.tb_Address.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_Address.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Address.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_Address.DefaultText = "";
            this.tb_Address.FillColor = System.Drawing.Color.White;
            this.tb_Address.HideSelection = true;
            this.tb_Address.IconLeft = null;
            this.tb_Address.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Address.IconPadding = 10;
            this.tb_Address.IconRight = null;
            this.tb_Address.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Address.Lines = new string[0];
            this.tb_Address.Location = new System.Drawing.Point(577, 75);
            this.tb_Address.MaxLength = 32767;
            this.tb_Address.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_Address.Modified = false;
            this.tb_Address.Multiline = false;
            this.tb_Address.Name = "tb_Address";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Address.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Silver;
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_Address.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Address.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Address.OnIdleState = stateProperties12;
            this.tb_Address.Padding = new System.Windows.Forms.Padding(3);
            this.tb_Address.PasswordChar = '\0';
            this.tb_Address.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_Address.PlaceholderText = "";
            this.tb_Address.ReadOnly = false;
            this.tb_Address.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_Address.SelectedText = "";
            this.tb_Address.SelectionLength = 0;
            this.tb_Address.SelectionStart = 0;
            this.tb_Address.ShortcutsEnabled = true;
            this.tb_Address.Size = new System.Drawing.Size(255, 38);
            this.tb_Address.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_Address.TabIndex = 39;
            this.tb_Address.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_Address.TextMarginBottom = 0;
            this.tb_Address.TextMarginLeft = 3;
            this.tb_Address.TextMarginTop = 1;
            this.tb_Address.TextPlaceholder = "";
            this.tb_Address.UseSystemPasswordChar = false;
            this.tb_Address.WordWrap = true;
            // 
            // tb_Name
            // 
            this.tb_Name.AcceptsReturn = false;
            this.tb_Name.AcceptsTab = false;
            this.tb_Name.AnimationSpeed = 200;
            this.tb_Name.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_Name.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_Name.AutoSizeHeight = true;
            this.tb_Name.BackColor = System.Drawing.Color.Transparent;
            this.tb_Name.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_Name.BackgroundImage")));
            this.tb_Name.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_Name.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_Name.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_Name.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_Name.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_Name.BorderRadius = 15;
            this.tb_Name.BorderThickness = 1;
            this.tb_Name.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_Name.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Name.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_Name.DefaultText = "";
            this.tb_Name.FillColor = System.Drawing.Color.White;
            this.tb_Name.HideSelection = true;
            this.tb_Name.IconLeft = null;
            this.tb_Name.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Name.IconPadding = 10;
            this.tb_Name.IconRight = null;
            this.tb_Name.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Name.Lines = new string[0];
            this.tb_Name.Location = new System.Drawing.Point(177, 75);
            this.tb_Name.MaxLength = 32767;
            this.tb_Name.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_Name.Modified = false;
            this.tb_Name.Multiline = false;
            this.tb_Name.Name = "tb_Name";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Name.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Silver;
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_Name.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Name.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Name.OnIdleState = stateProperties16;
            this.tb_Name.Padding = new System.Windows.Forms.Padding(3);
            this.tb_Name.PasswordChar = '\0';
            this.tb_Name.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_Name.PlaceholderText = "";
            this.tb_Name.ReadOnly = false;
            this.tb_Name.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_Name.SelectedText = "";
            this.tb_Name.SelectionLength = 0;
            this.tb_Name.SelectionStart = 0;
            this.tb_Name.ShortcutsEnabled = true;
            this.tb_Name.Size = new System.Drawing.Size(255, 38);
            this.tb_Name.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_Name.TabIndex = 36;
            this.tb_Name.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_Name.TextMarginBottom = 0;
            this.tb_Name.TextMarginLeft = 3;
            this.tb_Name.TextMarginTop = 1;
            this.tb_Name.TextPlaceholder = "";
            this.tb_Name.UseSystemPasswordChar = false;
            this.tb_Name.WordWrap = true;
            // 
            // bunifuPanel11
            // 
            this.bunifuPanel11.BackgroundColor = System.Drawing.Color.Gray;
            this.bunifuPanel11.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel11.BackgroundImage")));
            this.bunifuPanel11.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel11.BorderColor = System.Drawing.Color.Gray;
            this.bunifuPanel11.BorderRadius = 5;
            this.bunifuPanel11.BorderThickness = 0;
            this.bunifuPanel11.Enabled = false;
            this.bunifuPanel11.Location = new System.Drawing.Point(57, 75);
            this.bunifuPanel11.Name = "bunifuPanel11";
            this.bunifuPanel11.ShowBorders = true;
            this.bunifuPanel11.Size = new System.Drawing.Size(2, 250);
            this.bunifuPanel11.TabIndex = 34;
            // 
            // bt_Save
            // 
            this.bt_Save.AllowAnimations = true;
            this.bt_Save.AllowMouseEffects = true;
            this.bt_Save.AllowToggling = false;
            this.bt_Save.AnimationSpeed = 200;
            this.bt_Save.AutoGenerateColors = false;
            this.bt_Save.AutoRoundBorders = false;
            this.bt_Save.AutoSizeLeftIcon = true;
            this.bt_Save.AutoSizeRightIcon = true;
            this.bt_Save.BackColor = System.Drawing.Color.Transparent;
            this.bt_Save.BackColor1 = System.Drawing.Color.White;
            this.bt_Save.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bt_Save.BackgroundImage")));
            this.bt_Save.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Save.ButtonText = "Save";
            this.bt_Save.ButtonTextMarginLeft = 0;
            this.bt_Save.ColorContrastOnClick = 45;
            this.bt_Save.ColorContrastOnHover = 45;
            this.bt_Save.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bt_Save.CustomizableEdges = borderEdges4;
            this.bt_Save.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bt_Save.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_Save.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_Save.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_Save.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bt_Save.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bt_Save.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_Save.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bt_Save.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bt_Save.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bt_Save.IconMarginLeft = 11;
            this.bt_Save.IconPadding = 14;
            this.bt_Save.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bt_Save.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bt_Save.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bt_Save.IconSize = 5;
            this.bt_Save.IdleBorderColor = System.Drawing.Color.DimGray;
            this.bt_Save.IdleBorderRadius = 20;
            this.bt_Save.IdleBorderThickness = 2;
            this.bt_Save.IdleFillColor = System.Drawing.Color.White;
            this.bt_Save.IdleIconLeftImage = null;
            this.bt_Save.IdleIconRightImage = null;
            this.bt_Save.IndicateFocus = false;
            this.bt_Save.Location = new System.Drawing.Point(407, 310);
            this.bt_Save.Name = "bt_Save";
            this.bt_Save.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_Save.OnDisabledState.BorderRadius = 20;
            this.bt_Save.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Save.OnDisabledState.BorderThickness = 2;
            this.bt_Save.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_Save.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_Save.OnDisabledState.IconLeftImage = null;
            this.bt_Save.OnDisabledState.IconRightImage = null;
            this.bt_Save.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_Save.onHoverState.BorderRadius = 20;
            this.bt_Save.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Save.onHoverState.BorderThickness = 2;
            this.bt_Save.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_Save.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bt_Save.onHoverState.IconLeftImage = null;
            this.bt_Save.onHoverState.IconRightImage = null;
            this.bt_Save.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.bt_Save.OnIdleState.BorderRadius = 20;
            this.bt_Save.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Save.OnIdleState.BorderThickness = 2;
            this.bt_Save.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bt_Save.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_Save.OnIdleState.IconLeftImage = null;
            this.bt_Save.OnIdleState.IconRightImage = null;
            this.bt_Save.OnPressedState.BorderColor = System.Drawing.Color.Silver;
            this.bt_Save.OnPressedState.BorderRadius = 20;
            this.bt_Save.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Save.OnPressedState.BorderThickness = 2;
            this.bt_Save.OnPressedState.FillColor = System.Drawing.Color.White;
            this.bt_Save.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_Save.OnPressedState.IconLeftImage = null;
            this.bt_Save.OnPressedState.IconRightImage = null;
            this.bt_Save.Size = new System.Drawing.Size(172, 40);
            this.bt_Save.TabIndex = 42;
            this.bt_Save.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bt_Save.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bt_Save.TextMarginLeft = 0;
            this.bt_Save.TextPadding = new System.Windows.Forms.Padding(0);
            this.bt_Save.UseDefaultRadiusAndThickness = true;
            this.bt_Save.Click += new System.EventHandler(this.bt_Save_Click);
            // 
            // bunifuButton22
            // 
            this.bunifuButton22.AllowAnimations = true;
            this.bunifuButton22.AllowMouseEffects = true;
            this.bunifuButton22.AllowToggling = false;
            this.bunifuButton22.AnimationSpeed = 200;
            this.bunifuButton22.AutoGenerateColors = false;
            this.bunifuButton22.AutoRoundBorders = false;
            this.bunifuButton22.AutoSizeLeftIcon = true;
            this.bunifuButton22.AutoSizeRightIcon = true;
            this.bunifuButton22.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton22.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton22.BackgroundImage")));
            this.bunifuButton22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.ButtonText = "Clear";
            this.bunifuButton22.ButtonTextMarginLeft = 0;
            this.bunifuButton22.ColorContrastOnClick = 45;
            this.bunifuButton22.ColorContrastOnHover = 45;
            this.bunifuButton22.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton22.CustomizableEdges = borderEdges3;
            this.bunifuButton22.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton22.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton22.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bunifuButton22.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton22.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton22.IconMarginLeft = 11;
            this.bunifuButton22.IconPadding = 14;
            this.bunifuButton22.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton22.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton22.IconSize = 5;
            this.bunifuButton22.IdleBorderColor = System.Drawing.Color.DimGray;
            this.bunifuButton22.IdleBorderRadius = 20;
            this.bunifuButton22.IdleBorderThickness = 2;
            this.bunifuButton22.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton22.IdleIconLeftImage = null;
            this.bunifuButton22.IdleIconRightImage = null;
            this.bunifuButton22.IndicateFocus = false;
            this.bunifuButton22.Location = new System.Drawing.Point(177, 310);
            this.bunifuButton22.Name = "bunifuButton22";
            this.bunifuButton22.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.OnDisabledState.BorderRadius = 20;
            this.bunifuButton22.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnDisabledState.BorderThickness = 2;
            this.bunifuButton22.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.OnDisabledState.IconLeftImage = null;
            this.bunifuButton22.OnDisabledState.IconRightImage = null;
            this.bunifuButton22.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton22.onHoverState.BorderRadius = 20;
            this.bunifuButton22.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.onHoverState.BorderThickness = 2;
            this.bunifuButton22.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton22.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.onHoverState.IconLeftImage = null;
            this.bunifuButton22.onHoverState.IconRightImage = null;
            this.bunifuButton22.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.bunifuButton22.OnIdleState.BorderRadius = 20;
            this.bunifuButton22.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnIdleState.BorderThickness = 2;
            this.bunifuButton22.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton22.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bunifuButton22.OnIdleState.IconLeftImage = null;
            this.bunifuButton22.OnIdleState.IconRightImage = null;
            this.bunifuButton22.OnPressedState.BorderColor = System.Drawing.Color.Silver;
            this.bunifuButton22.OnPressedState.BorderRadius = 20;
            this.bunifuButton22.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnPressedState.BorderThickness = 2;
            this.bunifuButton22.OnPressedState.FillColor = System.Drawing.Color.White;
            this.bunifuButton22.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bunifuButton22.OnPressedState.IconLeftImage = null;
            this.bunifuButton22.OnPressedState.IconRightImage = null;
            this.bunifuButton22.Size = new System.Drawing.Size(172, 40);
            this.bunifuButton22.TabIndex = 43;
            this.bunifuButton22.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton22.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton22.TextMarginLeft = 0;
            this.bunifuButton22.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton22.UseDefaultRadiusAndThickness = true;
            this.bunifuButton22.Click += new System.EventHandler(this.bunifuButton22_Click);
            // 
            // bunifuButton23
            // 
            this.bunifuButton23.AllowAnimations = true;
            this.bunifuButton23.AllowMouseEffects = true;
            this.bunifuButton23.AllowToggling = false;
            this.bunifuButton23.AnimationSpeed = 200;
            this.bunifuButton23.AutoGenerateColors = false;
            this.bunifuButton23.AutoRoundBorders = false;
            this.bunifuButton23.AutoSizeLeftIcon = true;
            this.bunifuButton23.AutoSizeRightIcon = true;
            this.bunifuButton23.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton23.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.bunifuButton23.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton23.BackgroundImage")));
            this.bunifuButton23.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.ButtonText = "Exit";
            this.bunifuButton23.ButtonTextMarginLeft = 0;
            this.bunifuButton23.ColorContrastOnClick = 45;
            this.bunifuButton23.ColorContrastOnHover = 45;
            this.bunifuButton23.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton23.CustomizableEdges = borderEdges1;
            this.bunifuButton23.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton23.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton23.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton23.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton23.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton23.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton23.ForeColor = System.Drawing.Color.DarkGray;
            this.bunifuButton23.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton23.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton23.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton23.IconMarginLeft = 11;
            this.bunifuButton23.IconPadding = 14;
            this.bunifuButton23.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton23.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton23.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton23.IconSize = 5;
            this.bunifuButton23.IdleBorderColor = System.Drawing.Color.Black;
            this.bunifuButton23.IdleBorderRadius = 20;
            this.bunifuButton23.IdleBorderThickness = 2;
            this.bunifuButton23.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.bunifuButton23.IdleIconLeftImage = null;
            this.bunifuButton23.IdleIconRightImage = null;
            this.bunifuButton23.IndicateFocus = false;
            this.bunifuButton23.Location = new System.Drawing.Point(634, 310);
            this.bunifuButton23.Name = "bunifuButton23";
            this.bunifuButton23.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton23.OnDisabledState.BorderRadius = 20;
            this.bunifuButton23.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.OnDisabledState.BorderThickness = 2;
            this.bunifuButton23.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton23.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton23.OnDisabledState.IconLeftImage = null;
            this.bunifuButton23.OnDisabledState.IconRightImage = null;
            this.bunifuButton23.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton23.onHoverState.BorderRadius = 20;
            this.bunifuButton23.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.onHoverState.BorderThickness = 2;
            this.bunifuButton23.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton23.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton23.onHoverState.IconLeftImage = null;
            this.bunifuButton23.onHoverState.IconRightImage = null;
            this.bunifuButton23.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButton23.OnIdleState.BorderRadius = 20;
            this.bunifuButton23.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.OnIdleState.BorderThickness = 2;
            this.bunifuButton23.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.bunifuButton23.OnIdleState.ForeColor = System.Drawing.Color.DarkGray;
            this.bunifuButton23.OnIdleState.IconLeftImage = null;
            this.bunifuButton23.OnIdleState.IconRightImage = null;
            this.bunifuButton23.OnPressedState.BorderColor = System.Drawing.Color.Silver;
            this.bunifuButton23.OnPressedState.BorderRadius = 20;
            this.bunifuButton23.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.OnPressedState.BorderThickness = 2;
            this.bunifuButton23.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.bunifuButton23.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton23.OnPressedState.IconLeftImage = null;
            this.bunifuButton23.OnPressedState.IconRightImage = null;
            this.bunifuButton23.Size = new System.Drawing.Size(172, 40);
            this.bunifuButton23.TabIndex = 69;
            this.bunifuButton23.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton23.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton23.TextMarginLeft = 0;
            this.bunifuButton23.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton23.UseDefaultRadiusAndThickness = true;
            this.bunifuButton23.Click += new System.EventHandler(this.bt_Exit_Click);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bunifuPanel1.BorderRadius = 5;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 389);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(871, 11);
            this.bunifuPanel1.TabIndex = 70;
            // 
            // bunifuPanel7
            // 
            this.bunifuPanel7.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel7.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel7.BackgroundImage")));
            this.bunifuPanel7.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(33)))), ((int)(((byte)(70)))));
            this.bunifuPanel7.BorderRadius = 15;
            this.bunifuPanel7.BorderThickness = 1;
            this.bunifuPanel7.Controls.Add(this.DatePicker_DOB);
            this.bunifuPanel7.Location = new System.Drawing.Point(577, 176);
            this.bunifuPanel7.Name = "bunifuPanel7";
            this.bunifuPanel7.ShowBorders = true;
            this.bunifuPanel7.Size = new System.Drawing.Size(255, 39);
            this.bunifuPanel7.TabIndex = 176;
            // 
            // EditResume
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(868, 400);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.bunifuButton23);
            this.Controls.Add(this.bt_Exit);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.bunifuButton22);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.bt_Save);
            this.Controls.Add(this.bt_Clear);
            this.Controls.Add(this.bt_SaveResume);
            this.Controls.Add(this.tb_Phone);
            this.Controls.Add(this.tb_Email);
            this.Controls.Add(this.tb_Address);
            this.Controls.Add(this.tb_Name);
            this.Controls.Add(this.bunifuPanel11);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.bunifuPanel7);
            this.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "EditResume";
            this.Text = "EditResume";
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox1.PerformLayout();
            this.bunifuPanel7.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuTextBox tb_Phone;
        private Bunifu.UI.WinForms.BunifuTextBox tb_Email;
        private Bunifu.UI.WinForms.BunifuTextBox tb_Address;
        private Bunifu.UI.WinForms.BunifuTextBox tb_Name;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel11;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bt_Clear;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bt_SaveResume;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private Bunifu.UI.WinForms.BunifuDatePicker DatePicker_DOB;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuRadioButton Rb_Female;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label8;
        private Bunifu.UI.WinForms.BunifuRadioButton Rb_Male;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bt_Exit;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton23;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton22;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bt_Save;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel7;
    }
}