namespace QuanLyThuVienSach.GUI.GUI_ADMIN
{
    partial class FormAddBooks
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormAddBooks));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.label3 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.tb_Reprints = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_Author = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bt_Exit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bt_ClearBook = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bt_AddBook = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.tb_SellingPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_ImportPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel11 = new Bunifu.UI.WinForms.BunifuPanel();
            this.tb_NameBook = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.tb_Year = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.tb_NumberOfBook = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_Cetegory = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_ = new System.Windows.Forms.Label();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.panel1.Controls.Add(this.bunifuLabel1);
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(954, 48);
            this.panel1.TabIndex = 85;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.AutoSize = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Microsoft Tai Le", 11.25F);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.DarkGray;
            this.bunifuLabel1.Location = new System.Drawing.Point(15, 15);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(66, 19);
            this.bunifuLabel1.TabIndex = 88;
            this.bunifuLabel1.Text = "Add Book";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.White;
            this.label3.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label3.Location = new System.Drawing.Point(94, 187);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(46, 16);
            this.label3.TabIndex = 85;
            this.label3.Text = "Author";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.Color.White;
            this.label7.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label7.Location = new System.Drawing.Point(485, 86);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(115, 16);
            this.label7.TabIndex = 74;
            this.label7.Text = "Number of reprints";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.White;
            this.label6.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label6.Location = new System.Drawing.Point(486, 188);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(75, 16);
            this.label6.TabIndex = 73;
            this.label6.Text = "Selling price";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.White;
            this.label5.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label5.Location = new System.Drawing.Point(486, 137);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(77, 16);
            this.label5.TabIndex = 72;
            this.label5.Text = "Import price";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.White;
            this.label4.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label4.Location = new System.Drawing.Point(94, 236);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(90, 16);
            this.label4.TabIndex = 71;
            this.label4.Text = "Publishing year";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.White;
            this.label2.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label2.Location = new System.Drawing.Point(94, 86);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(72, 16);
            this.label2.TabIndex = 70;
            this.label2.Text = "Name Book";
            // 
            // tb_Reprints
            // 
            this.tb_Reprints.AcceptsReturn = false;
            this.tb_Reprints.AcceptsTab = false;
            this.tb_Reprints.AnimationSpeed = 200;
            this.tb_Reprints.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_Reprints.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_Reprints.AutoSizeHeight = true;
            this.tb_Reprints.BackColor = System.Drawing.Color.Transparent;
            this.tb_Reprints.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_Reprints.BackgroundImage")));
            this.tb_Reprints.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_Reprints.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_Reprints.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_Reprints.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_Reprints.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_Reprints.BorderRadius = 15;
            this.tb_Reprints.BorderThickness = 1;
            this.tb_Reprints.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_Reprints.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Reprints.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_Reprints.DefaultText = "";
            this.tb_Reprints.FillColor = System.Drawing.Color.White;
            this.tb_Reprints.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_Reprints.HideSelection = true;
            this.tb_Reprints.IconLeft = null;
            this.tb_Reprints.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Reprints.IconPadding = 10;
            this.tb_Reprints.IconRight = null;
            this.tb_Reprints.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Reprints.Lines = new string[0];
            this.tb_Reprints.Location = new System.Drawing.Point(614, 75);
            this.tb_Reprints.MaxLength = 32767;
            this.tb_Reprints.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_Reprints.Modified = false;
            this.tb_Reprints.Multiline = false;
            this.tb_Reprints.Name = "tb_Reprints";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Reprints.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Silver;
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_Reprints.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Reprints.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Reprints.OnIdleState = stateProperties16;
            this.tb_Reprints.Padding = new System.Windows.Forms.Padding(3);
            this.tb_Reprints.PasswordChar = '\0';
            this.tb_Reprints.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_Reprints.PlaceholderText = "Enter";
            this.tb_Reprints.ReadOnly = false;
            this.tb_Reprints.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_Reprints.SelectedText = "";
            this.tb_Reprints.SelectionLength = 0;
            this.tb_Reprints.SelectionStart = 0;
            this.tb_Reprints.ShortcutsEnabled = true;
            this.tb_Reprints.Size = new System.Drawing.Size(255, 37);
            this.tb_Reprints.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_Reprints.TabIndex = 80;
            this.tb_Reprints.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_Reprints.TextMarginBottom = 0;
            this.tb_Reprints.TextMarginLeft = 3;
            this.tb_Reprints.TextMarginTop = 0;
            this.tb_Reprints.TextPlaceholder = "Enter";
            this.tb_Reprints.UseSystemPasswordChar = false;
            this.tb_Reprints.WordWrap = true;
            // 
            // tb_Author
            // 
            this.tb_Author.AcceptsReturn = false;
            this.tb_Author.AcceptsTab = false;
            this.tb_Author.AnimationSpeed = 200;
            this.tb_Author.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_Author.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_Author.AutoSizeHeight = true;
            this.tb_Author.BackColor = System.Drawing.Color.Transparent;
            this.tb_Author.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_Author.BackgroundImage")));
            this.tb_Author.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_Author.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_Author.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_Author.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_Author.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_Author.BorderRadius = 15;
            this.tb_Author.BorderThickness = 1;
            this.tb_Author.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_Author.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Author.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_Author.DefaultText = "";
            this.tb_Author.FillColor = System.Drawing.Color.White;
            this.tb_Author.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_Author.HideSelection = true;
            this.tb_Author.IconLeft = null;
            this.tb_Author.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Author.IconPadding = 10;
            this.tb_Author.IconRight = null;
            this.tb_Author.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Author.Lines = new string[0];
            this.tb_Author.Location = new System.Drawing.Point(195, 174);
            this.tb_Author.MaxLength = 32767;
            this.tb_Author.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_Author.Modified = false;
            this.tb_Author.Multiline = false;
            this.tb_Author.Name = "tb_Author";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Author.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Silver;
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_Author.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Author.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Author.OnIdleState = stateProperties20;
            this.tb_Author.Padding = new System.Windows.Forms.Padding(3);
            this.tb_Author.PasswordChar = '\0';
            this.tb_Author.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_Author.PlaceholderText = "Enter";
            this.tb_Author.ReadOnly = false;
            this.tb_Author.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_Author.SelectedText = "";
            this.tb_Author.SelectionLength = 0;
            this.tb_Author.SelectionStart = 0;
            this.tb_Author.ShortcutsEnabled = true;
            this.tb_Author.Size = new System.Drawing.Size(255, 37);
            this.tb_Author.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_Author.TabIndex = 86;
            this.tb_Author.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_Author.TextMarginBottom = 0;
            this.tb_Author.TextMarginLeft = 3;
            this.tb_Author.TextMarginTop = 0;
            this.tb_Author.TextPlaceholder = "Enter";
            this.tb_Author.UseSystemPasswordChar = false;
            this.tb_Author.WordWrap = true;
            // 
            // bt_Exit
            // 
            this.bt_Exit.AllowAnimations = true;
            this.bt_Exit.AllowMouseEffects = true;
            this.bt_Exit.AllowToggling = false;
            this.bt_Exit.AnimationSpeed = 200;
            this.bt_Exit.AutoGenerateColors = false;
            this.bt_Exit.AutoRoundBorders = false;
            this.bt_Exit.AutoSizeLeftIcon = true;
            this.bt_Exit.AutoSizeRightIcon = true;
            this.bt_Exit.BackColor = System.Drawing.Color.Transparent;
            this.bt_Exit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.bt_Exit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bt_Exit.BackgroundImage")));
            this.bt_Exit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.ButtonText = "Exit";
            this.bt_Exit.ButtonTextMarginLeft = 0;
            this.bt_Exit.ColorContrastOnClick = 45;
            this.bt_Exit.ColorContrastOnHover = 45;
            this.bt_Exit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bt_Exit.CustomizableEdges = borderEdges1;
            this.bt_Exit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bt_Exit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_Exit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_Exit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_Exit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bt_Exit.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bt_Exit.ForeColor = System.Drawing.Color.DarkGray;
            this.bt_Exit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bt_Exit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bt_Exit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bt_Exit.IconMarginLeft = 11;
            this.bt_Exit.IconPadding = 14;
            this.bt_Exit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bt_Exit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bt_Exit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bt_Exit.IconSize = 5;
            this.bt_Exit.IdleBorderColor = System.Drawing.Color.Black;
            this.bt_Exit.IdleBorderRadius = 30;
            this.bt_Exit.IdleBorderThickness = 2;
            this.bt_Exit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.bt_Exit.IdleIconLeftImage = null;
            this.bt_Exit.IdleIconRightImage = null;
            this.bt_Exit.IndicateFocus = false;
            this.bt_Exit.Location = new System.Drawing.Point(637, 363);
            this.bt_Exit.Name = "bt_Exit";
            this.bt_Exit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_Exit.OnDisabledState.BorderRadius = 30;
            this.bt_Exit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.OnDisabledState.BorderThickness = 2;
            this.bt_Exit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_Exit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_Exit.OnDisabledState.IconLeftImage = null;
            this.bt_Exit.OnDisabledState.IconRightImage = null;
            this.bt_Exit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_Exit.onHoverState.BorderRadius = 30;
            this.bt_Exit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.onHoverState.BorderThickness = 2;
            this.bt_Exit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_Exit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bt_Exit.onHoverState.IconLeftImage = null;
            this.bt_Exit.onHoverState.IconRightImage = null;
            this.bt_Exit.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bt_Exit.OnIdleState.BorderRadius = 30;
            this.bt_Exit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.OnIdleState.BorderThickness = 2;
            this.bt_Exit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.bt_Exit.OnIdleState.ForeColor = System.Drawing.Color.DarkGray;
            this.bt_Exit.OnIdleState.IconLeftImage = null;
            this.bt_Exit.OnIdleState.IconRightImage = null;
            this.bt_Exit.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.bt_Exit.OnPressedState.BorderRadius = 30;
            this.bt_Exit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_Exit.OnPressedState.BorderThickness = 2;
            this.bt_Exit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.bt_Exit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bt_Exit.OnPressedState.IconLeftImage = null;
            this.bt_Exit.OnPressedState.IconRightImage = null;
            this.bt_Exit.Size = new System.Drawing.Size(205, 40);
            this.bt_Exit.TabIndex = 83;
            this.bt_Exit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bt_Exit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bt_Exit.TextMarginLeft = 0;
            this.bt_Exit.TextPadding = new System.Windows.Forms.Padding(0);
            this.bt_Exit.UseDefaultRadiusAndThickness = true;
            this.bt_Exit.Click += new System.EventHandler(this.bt_Exit_Click);
            // 
            // bt_ClearBook
            // 
            this.bt_ClearBook.AllowAnimations = true;
            this.bt_ClearBook.AllowMouseEffects = true;
            this.bt_ClearBook.AllowToggling = false;
            this.bt_ClearBook.AnimationSpeed = 200;
            this.bt_ClearBook.AutoGenerateColors = false;
            this.bt_ClearBook.AutoRoundBorders = false;
            this.bt_ClearBook.AutoSizeLeftIcon = true;
            this.bt_ClearBook.AutoSizeRightIcon = true;
            this.bt_ClearBook.BackColor = System.Drawing.Color.Transparent;
            this.bt_ClearBook.BackColor1 = System.Drawing.Color.White;
            this.bt_ClearBook.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bt_ClearBook.BackgroundImage")));
            this.bt_ClearBook.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_ClearBook.ButtonText = "Clear";
            this.bt_ClearBook.ButtonTextMarginLeft = 0;
            this.bt_ClearBook.ColorContrastOnClick = 45;
            this.bt_ClearBook.ColorContrastOnHover = 45;
            this.bt_ClearBook.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bt_ClearBook.CustomizableEdges = borderEdges2;
            this.bt_ClearBook.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bt_ClearBook.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_ClearBook.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_ClearBook.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_ClearBook.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bt_ClearBook.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bt_ClearBook.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_ClearBook.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bt_ClearBook.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bt_ClearBook.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bt_ClearBook.IconMarginLeft = 11;
            this.bt_ClearBook.IconPadding = 14;
            this.bt_ClearBook.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bt_ClearBook.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bt_ClearBook.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bt_ClearBook.IconSize = 5;
            this.bt_ClearBook.IdleBorderColor = System.Drawing.Color.DimGray;
            this.bt_ClearBook.IdleBorderRadius = 30;
            this.bt_ClearBook.IdleBorderThickness = 2;
            this.bt_ClearBook.IdleFillColor = System.Drawing.Color.White;
            this.bt_ClearBook.IdleIconLeftImage = null;
            this.bt_ClearBook.IdleIconRightImage = null;
            this.bt_ClearBook.IndicateFocus = false;
            this.bt_ClearBook.Location = new System.Drawing.Point(141, 363);
            this.bt_ClearBook.Name = "bt_ClearBook";
            this.bt_ClearBook.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_ClearBook.OnDisabledState.BorderRadius = 30;
            this.bt_ClearBook.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_ClearBook.OnDisabledState.BorderThickness = 2;
            this.bt_ClearBook.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_ClearBook.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_ClearBook.OnDisabledState.IconLeftImage = null;
            this.bt_ClearBook.OnDisabledState.IconRightImage = null;
            this.bt_ClearBook.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_ClearBook.onHoverState.BorderRadius = 30;
            this.bt_ClearBook.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_ClearBook.onHoverState.BorderThickness = 2;
            this.bt_ClearBook.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_ClearBook.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bt_ClearBook.onHoverState.IconLeftImage = null;
            this.bt_ClearBook.onHoverState.IconRightImage = null;
            this.bt_ClearBook.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.bt_ClearBook.OnIdleState.BorderRadius = 30;
            this.bt_ClearBook.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_ClearBook.OnIdleState.BorderThickness = 2;
            this.bt_ClearBook.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bt_ClearBook.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_ClearBook.OnIdleState.IconLeftImage = null;
            this.bt_ClearBook.OnIdleState.IconRightImage = null;
            this.bt_ClearBook.OnPressedState.BorderColor = System.Drawing.Color.Silver;
            this.bt_ClearBook.OnPressedState.BorderRadius = 30;
            this.bt_ClearBook.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_ClearBook.OnPressedState.BorderThickness = 2;
            this.bt_ClearBook.OnPressedState.FillColor = System.Drawing.Color.White;
            this.bt_ClearBook.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_ClearBook.OnPressedState.IconLeftImage = null;
            this.bt_ClearBook.OnPressedState.IconRightImage = null;
            this.bt_ClearBook.Size = new System.Drawing.Size(205, 40);
            this.bt_ClearBook.TabIndex = 82;
            this.bt_ClearBook.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bt_ClearBook.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bt_ClearBook.TextMarginLeft = 0;
            this.bt_ClearBook.TextPadding = new System.Windows.Forms.Padding(0);
            this.bt_ClearBook.UseDefaultRadiusAndThickness = true;
            this.bt_ClearBook.Click += new System.EventHandler(this.bt_ClearBook_Click);
            // 
            // bt_AddBook
            // 
            this.bt_AddBook.AllowAnimations = true;
            this.bt_AddBook.AllowMouseEffects = true;
            this.bt_AddBook.AllowToggling = false;
            this.bt_AddBook.AnimationSpeed = 200;
            this.bt_AddBook.AutoGenerateColors = false;
            this.bt_AddBook.AutoRoundBorders = false;
            this.bt_AddBook.AutoSizeLeftIcon = true;
            this.bt_AddBook.AutoSizeRightIcon = true;
            this.bt_AddBook.BackColor = System.Drawing.Color.Transparent;
            this.bt_AddBook.BackColor1 = System.Drawing.Color.White;
            this.bt_AddBook.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bt_AddBook.BackgroundImage")));
            this.bt_AddBook.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_AddBook.ButtonText = "ADD";
            this.bt_AddBook.ButtonTextMarginLeft = 0;
            this.bt_AddBook.ColorContrastOnClick = 45;
            this.bt_AddBook.ColorContrastOnHover = 45;
            this.bt_AddBook.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bt_AddBook.CustomizableEdges = borderEdges3;
            this.bt_AddBook.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bt_AddBook.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_AddBook.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_AddBook.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_AddBook.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bt_AddBook.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bt_AddBook.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_AddBook.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bt_AddBook.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bt_AddBook.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bt_AddBook.IconMarginLeft = 11;
            this.bt_AddBook.IconPadding = 14;
            this.bt_AddBook.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bt_AddBook.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bt_AddBook.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bt_AddBook.IconSize = 5;
            this.bt_AddBook.IdleBorderColor = System.Drawing.Color.DimGray;
            this.bt_AddBook.IdleBorderRadius = 30;
            this.bt_AddBook.IdleBorderThickness = 2;
            this.bt_AddBook.IdleFillColor = System.Drawing.Color.White;
            this.bt_AddBook.IdleIconLeftImage = null;
            this.bt_AddBook.IdleIconRightImage = null;
            this.bt_AddBook.IndicateFocus = false;
            this.bt_AddBook.Location = new System.Drawing.Point(389, 363);
            this.bt_AddBook.Name = "bt_AddBook";
            this.bt_AddBook.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt_AddBook.OnDisabledState.BorderRadius = 30;
            this.bt_AddBook.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_AddBook.OnDisabledState.BorderThickness = 2;
            this.bt_AddBook.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt_AddBook.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt_AddBook.OnDisabledState.IconLeftImage = null;
            this.bt_AddBook.OnDisabledState.IconRightImage = null;
            this.bt_AddBook.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_AddBook.onHoverState.BorderRadius = 30;
            this.bt_AddBook.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_AddBook.onHoverState.BorderThickness = 2;
            this.bt_AddBook.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bt_AddBook.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bt_AddBook.onHoverState.IconLeftImage = null;
            this.bt_AddBook.onHoverState.IconRightImage = null;
            this.bt_AddBook.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.bt_AddBook.OnIdleState.BorderRadius = 30;
            this.bt_AddBook.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_AddBook.OnIdleState.BorderThickness = 2;
            this.bt_AddBook.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bt_AddBook.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_AddBook.OnIdleState.IconLeftImage = null;
            this.bt_AddBook.OnIdleState.IconRightImage = null;
            this.bt_AddBook.OnPressedState.BorderColor = System.Drawing.Color.Silver;
            this.bt_AddBook.OnPressedState.BorderRadius = 30;
            this.bt_AddBook.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt_AddBook.OnPressedState.BorderThickness = 2;
            this.bt_AddBook.OnPressedState.FillColor = System.Drawing.Color.White;
            this.bt_AddBook.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bt_AddBook.OnPressedState.IconLeftImage = null;
            this.bt_AddBook.OnPressedState.IconRightImage = null;
            this.bt_AddBook.Size = new System.Drawing.Size(205, 40);
            this.bt_AddBook.TabIndex = 81;
            this.bt_AddBook.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bt_AddBook.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bt_AddBook.TextMarginLeft = 0;
            this.bt_AddBook.TextPadding = new System.Windows.Forms.Padding(0);
            this.bt_AddBook.UseDefaultRadiusAndThickness = true;
            this.bt_AddBook.Click += new System.EventHandler(this.bt_AddBook_Click);
            // 
            // tb_SellingPrice
            // 
            this.tb_SellingPrice.AcceptsReturn = false;
            this.tb_SellingPrice.AcceptsTab = false;
            this.tb_SellingPrice.AnimationSpeed = 200;
            this.tb_SellingPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_SellingPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_SellingPrice.AutoSizeHeight = true;
            this.tb_SellingPrice.BackColor = System.Drawing.Color.Transparent;
            this.tb_SellingPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_SellingPrice.BackgroundImage")));
            this.tb_SellingPrice.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_SellingPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_SellingPrice.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_SellingPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_SellingPrice.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_SellingPrice.BorderRadius = 15;
            this.tb_SellingPrice.BorderThickness = 1;
            this.tb_SellingPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_SellingPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_SellingPrice.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_SellingPrice.DefaultText = "";
            this.tb_SellingPrice.FillColor = System.Drawing.Color.White;
            this.tb_SellingPrice.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_SellingPrice.HideSelection = true;
            this.tb_SellingPrice.IconLeft = null;
            this.tb_SellingPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_SellingPrice.IconPadding = 10;
            this.tb_SellingPrice.IconRight = null;
            this.tb_SellingPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_SellingPrice.Lines = new string[0];
            this.tb_SellingPrice.Location = new System.Drawing.Point(614, 174);
            this.tb_SellingPrice.MaxLength = 32767;
            this.tb_SellingPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_SellingPrice.Modified = false;
            this.tb_SellingPrice.Multiline = false;
            this.tb_SellingPrice.Name = "tb_SellingPrice";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_SellingPrice.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Silver;
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_SellingPrice.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_SellingPrice.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_SellingPrice.OnIdleState = stateProperties24;
            this.tb_SellingPrice.Padding = new System.Windows.Forms.Padding(3);
            this.tb_SellingPrice.PasswordChar = '\0';
            this.tb_SellingPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_SellingPrice.PlaceholderText = "Enter";
            this.tb_SellingPrice.ReadOnly = false;
            this.tb_SellingPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_SellingPrice.SelectedText = "";
            this.tb_SellingPrice.SelectionLength = 0;
            this.tb_SellingPrice.SelectionStart = 0;
            this.tb_SellingPrice.ShortcutsEnabled = true;
            this.tb_SellingPrice.Size = new System.Drawing.Size(255, 37);
            this.tb_SellingPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_SellingPrice.TabIndex = 79;
            this.tb_SellingPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_SellingPrice.TextMarginBottom = 0;
            this.tb_SellingPrice.TextMarginLeft = 3;
            this.tb_SellingPrice.TextMarginTop = 0;
            this.tb_SellingPrice.TextPlaceholder = "Enter";
            this.tb_SellingPrice.UseSystemPasswordChar = false;
            this.tb_SellingPrice.WordWrap = true;
            // 
            // tb_ImportPrice
            // 
            this.tb_ImportPrice.AcceptsReturn = false;
            this.tb_ImportPrice.AcceptsTab = false;
            this.tb_ImportPrice.AnimationSpeed = 200;
            this.tb_ImportPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_ImportPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_ImportPrice.AutoSizeHeight = true;
            this.tb_ImportPrice.BackColor = System.Drawing.Color.Transparent;
            this.tb_ImportPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_ImportPrice.BackgroundImage")));
            this.tb_ImportPrice.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_ImportPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_ImportPrice.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_ImportPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_ImportPrice.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_ImportPrice.BorderRadius = 15;
            this.tb_ImportPrice.BorderThickness = 1;
            this.tb_ImportPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_ImportPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_ImportPrice.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_ImportPrice.DefaultText = "";
            this.tb_ImportPrice.FillColor = System.Drawing.Color.White;
            this.tb_ImportPrice.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_ImportPrice.HideSelection = true;
            this.tb_ImportPrice.IconLeft = null;
            this.tb_ImportPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_ImportPrice.IconPadding = 10;
            this.tb_ImportPrice.IconRight = null;
            this.tb_ImportPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_ImportPrice.Lines = new string[0];
            this.tb_ImportPrice.Location = new System.Drawing.Point(614, 124);
            this.tb_ImportPrice.MaxLength = 32767;
            this.tb_ImportPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_ImportPrice.Modified = false;
            this.tb_ImportPrice.Multiline = false;
            this.tb_ImportPrice.Name = "tb_ImportPrice";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_ImportPrice.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Silver;
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_ImportPrice.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_ImportPrice.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_ImportPrice.OnIdleState = stateProperties28;
            this.tb_ImportPrice.Padding = new System.Windows.Forms.Padding(3);
            this.tb_ImportPrice.PasswordChar = '\0';
            this.tb_ImportPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_ImportPrice.PlaceholderText = "Enter";
            this.tb_ImportPrice.ReadOnly = false;
            this.tb_ImportPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_ImportPrice.SelectedText = "";
            this.tb_ImportPrice.SelectionLength = 0;
            this.tb_ImportPrice.SelectionStart = 0;
            this.tb_ImportPrice.ShortcutsEnabled = true;
            this.tb_ImportPrice.Size = new System.Drawing.Size(255, 37);
            this.tb_ImportPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_ImportPrice.TabIndex = 78;
            this.tb_ImportPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_ImportPrice.TextMarginBottom = 0;
            this.tb_ImportPrice.TextMarginLeft = 3;
            this.tb_ImportPrice.TextMarginTop = 0;
            this.tb_ImportPrice.TextPlaceholder = "Enter";
            this.tb_ImportPrice.UseSystemPasswordChar = false;
            this.tb_ImportPrice.WordWrap = true;
            // 
            // bunifuPanel11
            // 
            this.bunifuPanel11.BackgroundColor = System.Drawing.Color.Gray;
            this.bunifuPanel11.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel11.BackgroundImage")));
            this.bunifuPanel11.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel11.BorderColor = System.Drawing.Color.Gray;
            this.bunifuPanel11.BorderRadius = 5;
            this.bunifuPanel11.BorderThickness = 0;
            this.bunifuPanel11.Enabled = false;
            this.bunifuPanel11.Location = new System.Drawing.Point(57, 75);
            this.bunifuPanel11.Name = "bunifuPanel11";
            this.bunifuPanel11.ShowBorders = true;
            this.bunifuPanel11.Size = new System.Drawing.Size(2, 250);
            this.bunifuPanel11.TabIndex = 75;
            // 
            // tb_NameBook
            // 
            this.tb_NameBook.AcceptsReturn = false;
            this.tb_NameBook.AcceptsTab = false;
            this.tb_NameBook.AnimationSpeed = 200;
            this.tb_NameBook.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_NameBook.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_NameBook.AutoSizeHeight = true;
            this.tb_NameBook.BackColor = System.Drawing.Color.Transparent;
            this.tb_NameBook.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_NameBook.BackgroundImage")));
            this.tb_NameBook.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_NameBook.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_NameBook.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_NameBook.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_NameBook.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_NameBook.BorderRadius = 15;
            this.tb_NameBook.BorderThickness = 1;
            this.tb_NameBook.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_NameBook.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NameBook.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_NameBook.DefaultText = "";
            this.tb_NameBook.FillColor = System.Drawing.Color.White;
            this.tb_NameBook.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_NameBook.HideSelection = true;
            this.tb_NameBook.IconLeft = null;
            this.tb_NameBook.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NameBook.IconPadding = 10;
            this.tb_NameBook.IconRight = null;
            this.tb_NameBook.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NameBook.Lines = new string[0];
            this.tb_NameBook.Location = new System.Drawing.Point(195, 75);
            this.tb_NameBook.MaxLength = 32767;
            this.tb_NameBook.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_NameBook.Modified = false;
            this.tb_NameBook.Multiline = false;
            this.tb_NameBook.Name = "tb_NameBook";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NameBook.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Silver;
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_NameBook.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NameBook.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NameBook.OnIdleState = stateProperties32;
            this.tb_NameBook.Padding = new System.Windows.Forms.Padding(3);
            this.tb_NameBook.PasswordChar = '\0';
            this.tb_NameBook.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_NameBook.PlaceholderText = "Enter";
            this.tb_NameBook.ReadOnly = false;
            this.tb_NameBook.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_NameBook.SelectedText = "";
            this.tb_NameBook.SelectionLength = 0;
            this.tb_NameBook.SelectionStart = 0;
            this.tb_NameBook.ShortcutsEnabled = true;
            this.tb_NameBook.Size = new System.Drawing.Size(255, 37);
            this.tb_NameBook.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_NameBook.TabIndex = 77;
            this.tb_NameBook.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_NameBook.TextMarginBottom = 0;
            this.tb_NameBook.TextMarginLeft = 3;
            this.tb_NameBook.TextMarginTop = 0;
            this.tb_NameBook.TextPlaceholder = "Enter";
            this.tb_NameBook.UseSystemPasswordChar = false;
            this.tb_NameBook.WordWrap = true;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
            this.bunifuPanel1.BorderRadius = 5;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 479);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(956, 10);
            this.bunifuPanel1.TabIndex = 87;
            // 
            // tb_Year
            // 
            this.tb_Year.AcceptsReturn = false;
            this.tb_Year.AcceptsTab = false;
            this.tb_Year.AnimationSpeed = 200;
            this.tb_Year.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_Year.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_Year.AutoSizeHeight = true;
            this.tb_Year.BackColor = System.Drawing.Color.Transparent;
            this.tb_Year.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_Year.BackgroundImage")));
            this.tb_Year.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_Year.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_Year.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_Year.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_Year.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_Year.BorderRadius = 15;
            this.tb_Year.BorderThickness = 1;
            this.tb_Year.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_Year.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Year.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_Year.DefaultText = "";
            this.tb_Year.FillColor = System.Drawing.Color.White;
            this.tb_Year.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_Year.HideSelection = true;
            this.tb_Year.IconLeft = null;
            this.tb_Year.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Year.IconPadding = 10;
            this.tb_Year.IconRight = null;
            this.tb_Year.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Year.Lines = new string[0];
            this.tb_Year.Location = new System.Drawing.Point(195, 226);
            this.tb_Year.MaxLength = 32767;
            this.tb_Year.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_Year.Modified = false;
            this.tb_Year.Multiline = false;
            this.tb_Year.Name = "tb_Year";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Year.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Silver;
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_Year.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Year.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Year.OnIdleState = stateProperties12;
            this.tb_Year.Padding = new System.Windows.Forms.Padding(3);
            this.tb_Year.PasswordChar = '\0';
            this.tb_Year.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_Year.PlaceholderText = "Enter";
            this.tb_Year.ReadOnly = false;
            this.tb_Year.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_Year.SelectedText = "";
            this.tb_Year.SelectionLength = 0;
            this.tb_Year.SelectionStart = 0;
            this.tb_Year.ShortcutsEnabled = true;
            this.tb_Year.Size = new System.Drawing.Size(255, 37);
            this.tb_Year.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_Year.TabIndex = 88;
            this.tb_Year.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_Year.TextMarginBottom = 0;
            this.tb_Year.TextMarginLeft = 3;
            this.tb_Year.TextMarginTop = 0;
            this.tb_Year.TextPlaceholder = "Enter";
            this.tb_Year.UseSystemPasswordChar = false;
            this.tb_Year.WordWrap = true;
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.BackColor = System.Drawing.Color.White;
            this.label8.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.label8.Location = new System.Drawing.Point(485, 236);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(100, 16);
            this.label8.TabIndex = 89;
            this.label8.Text = "Number of Book";
            // 
            // tb_NumberOfBook
            // 
            this.tb_NumberOfBook.AcceptsReturn = false;
            this.tb_NumberOfBook.AcceptsTab = false;
            this.tb_NumberOfBook.AnimationSpeed = 200;
            this.tb_NumberOfBook.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_NumberOfBook.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_NumberOfBook.AutoSizeHeight = true;
            this.tb_NumberOfBook.BackColor = System.Drawing.Color.Transparent;
            this.tb_NumberOfBook.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_NumberOfBook.BackgroundImage")));
            this.tb_NumberOfBook.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_NumberOfBook.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_NumberOfBook.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_NumberOfBook.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_NumberOfBook.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_NumberOfBook.BorderRadius = 15;
            this.tb_NumberOfBook.BorderThickness = 1;
            this.tb_NumberOfBook.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_NumberOfBook.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NumberOfBook.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_NumberOfBook.DefaultText = "";
            this.tb_NumberOfBook.FillColor = System.Drawing.Color.White;
            this.tb_NumberOfBook.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_NumberOfBook.HideSelection = true;
            this.tb_NumberOfBook.IconLeft = null;
            this.tb_NumberOfBook.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NumberOfBook.IconPadding = 10;
            this.tb_NumberOfBook.IconRight = null;
            this.tb_NumberOfBook.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_NumberOfBook.Lines = new string[0];
            this.tb_NumberOfBook.Location = new System.Drawing.Point(614, 226);
            this.tb_NumberOfBook.MaxLength = 32767;
            this.tb_NumberOfBook.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_NumberOfBook.Modified = false;
            this.tb_NumberOfBook.Multiline = false;
            this.tb_NumberOfBook.Name = "tb_NumberOfBook";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NumberOfBook.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Silver;
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_NumberOfBook.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NumberOfBook.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_NumberOfBook.OnIdleState = stateProperties8;
            this.tb_NumberOfBook.Padding = new System.Windows.Forms.Padding(3);
            this.tb_NumberOfBook.PasswordChar = '\0';
            this.tb_NumberOfBook.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_NumberOfBook.PlaceholderText = "Enter";
            this.tb_NumberOfBook.ReadOnly = false;
            this.tb_NumberOfBook.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_NumberOfBook.SelectedText = "";
            this.tb_NumberOfBook.SelectionLength = 0;
            this.tb_NumberOfBook.SelectionStart = 0;
            this.tb_NumberOfBook.ShortcutsEnabled = true;
            this.tb_NumberOfBook.Size = new System.Drawing.Size(255, 37);
            this.tb_NumberOfBook.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_NumberOfBook.TabIndex = 90;
            this.tb_NumberOfBook.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_NumberOfBook.TextMarginBottom = 0;
            this.tb_NumberOfBook.TextMarginLeft = 3;
            this.tb_NumberOfBook.TextMarginTop = 0;
            this.tb_NumberOfBook.TextPlaceholder = "Enter";
            this.tb_NumberOfBook.UseSystemPasswordChar = false;
            this.tb_NumberOfBook.WordWrap = true;
            // 
            // tb_Cetegory
            // 
            this.tb_Cetegory.AcceptsReturn = false;
            this.tb_Cetegory.AcceptsTab = false;
            this.tb_Cetegory.AnimationSpeed = 200;
            this.tb_Cetegory.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_Cetegory.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_Cetegory.AutoSizeHeight = true;
            this.tb_Cetegory.BackColor = System.Drawing.Color.Transparent;
            this.tb_Cetegory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_Cetegory.BackgroundImage")));
            this.tb_Cetegory.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.tb_Cetegory.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_Cetegory.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tb_Cetegory.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_Cetegory.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_Cetegory.BorderRadius = 15;
            this.tb_Cetegory.BorderThickness = 1;
            this.tb_Cetegory.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_Cetegory.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Cetegory.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_Cetegory.DefaultText = "";
            this.tb_Cetegory.FillColor = System.Drawing.Color.White;
            this.tb_Cetegory.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            this.tb_Cetegory.HideSelection = true;
            this.tb_Cetegory.IconLeft = null;
            this.tb_Cetegory.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Cetegory.IconPadding = 10;
            this.tb_Cetegory.IconRight = null;
            this.tb_Cetegory.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_Cetegory.Lines = new string[0];
            this.tb_Cetegory.Location = new System.Drawing.Point(195, 124);
            this.tb_Cetegory.MaxLength = 32767;
            this.tb_Cetegory.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_Cetegory.Modified = false;
            this.tb_Cetegory.Multiline = false;
            this.tb_Cetegory.Name = "tb_Cetegory";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Cetegory.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Silver;
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_Cetegory.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Cetegory.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(70)))));
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_Cetegory.OnIdleState = stateProperties4;
            this.tb_Cetegory.Padding = new System.Windows.Forms.Padding(3);
            this.tb_Cetegory.PasswordChar = '\0';
            this.tb_Cetegory.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_Cetegory.PlaceholderText = "Enter";
            this.tb_Cetegory.ReadOnly = false;
            this.tb_Cetegory.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_Cetegory.SelectedText = "";
            this.tb_Cetegory.SelectionLength = 0;
            this.tb_Cetegory.SelectionStart = 0;
            this.tb_Cetegory.ShortcutsEnabled = true;
            this.tb_Cetegory.Size = new System.Drawing.Size(255, 37);
            this.tb_Cetegory.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_Cetegory.TabIndex = 174;
            this.tb_Cetegory.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_Cetegory.TextMarginBottom = 0;
            this.tb_Cetegory.TextMarginLeft = 3;
            this.tb_Cetegory.TextMarginTop = 0;
            this.tb_Cetegory.TextPlaceholder = "Enter";
            this.tb_Cetegory.UseSystemPasswordChar = false;
            this.tb_Cetegory.WordWrap = true;
            // 
            // tb_
            // 
            this.tb_.AutoSize = true;
            this.tb_.BackColor = System.Drawing.Color.White;
            this.tb_.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tb_.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(55)))));
            this.tb_.Location = new System.Drawing.Point(94, 137);
            this.tb_.Name = "tb_";
            this.tb_.Size = new System.Drawing.Size(58, 16);
            this.tb_.TabIndex = 173;
            this.tb_.Text = "Cetegory";
            // 
            // FormAddBooks
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(955, 489);
            this.Controls.Add(this.tb_Cetegory);
            this.Controls.Add(this.tb_);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.tb_NumberOfBook);
            this.Controls.Add(this.tb_Year);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.tb_Reprints);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.tb_Author);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.bt_Exit);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.bt_ClearBook);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.bt_AddBook);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.tb_SellingPrice);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.tb_ImportPrice);
            this.Controls.Add(this.bunifuPanel11);
            this.Controls.Add(this.tb_NameBook);
            this.Font = new System.Drawing.Font("Microsoft Tai Le", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "FormAddBooks";
            this.Text = "FormAddBooks";
            this.panel1.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.Panel panel1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuTextBox tb_Reprints;
        private Bunifu.UI.WinForms.BunifuTextBox tb_Author;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bt_Exit;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bt_ClearBook;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bt_AddBook;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox tb_SellingPrice;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuTextBox tb_ImportPrice;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel11;
        private Bunifu.UI.WinForms.BunifuTextBox tb_NameBook;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuTextBox tb_Year;
        private System.Windows.Forms.Label label8;
        private Bunifu.UI.WinForms.BunifuTextBox tb_NumberOfBook;
        private Bunifu.UI.WinForms.BunifuTextBox tb_Cetegory;
        private System.Windows.Forms.Label tb_;
    }
}